pages = [{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/little/cli.html","n":"little.cli","t":"package little.cli","d":"little/cli"},
{"l":"api/little/cli.html","n":"Optionable","t":"type Optionable = Option | OptionGroup","d":"little/cli"},
{"l":"api/little/cli/Application.html","n":"Application","t":"trait Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"usage","t":"def usage: String","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"usage","t":"def usage(syntax: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"options","t":"def options: Options","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"options","t":"def options(opts: Options): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"options","t":"def options(opts: Optionable*): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOptions","t":"def addOptions(opts: Optionable*): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOption","t":"def addOption(opt: Option): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOption","t":"def addOption(opt: String, description: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOption","t":"def addOption(opt: String, hasArg: Boolean, description: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOption","t":"def addOption(opt: String, longOpt: String, hasArg: Boolean, description: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOptionGroup","t":"def addOptionGroup(group: OptionGroup): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"addOptionGroup","t":"def addOptionGroup(opts: Option*): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"header","t":"def header: String","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"header","t":"def header(text: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"footer","t":"def footer: String","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"footer","t":"def footer(text: String): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"formatter","t":"def formatter: HelpFormatter","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"formatter","t":"def formatter(fmt: HelpFormatter): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"width","t":"def width: Int","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"width","t":"def width(max: Int): Application","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"help","t":"def help: String","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"printHelp","t":"def printHelp(): Unit","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"printHelp","t":"def printHelp(out: OutputStream): Unit","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"printHelp","t":"def printHelp(out: PrintWriter): Unit","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"parse","t":"def parse(args: Array[String]): CommandLine","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"parse","t":"def parse(args: Array[String], stoppable: Boolean): CommandLine","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"tryParse","t":"def tryParse(args: Array[String]): Try[CommandLine]","d":"little/cli/Application"},
{"l":"api/little/cli/Application.html","n":"tryParse","t":"def tryParse(args: Array[String], stoppable: Boolean): Try[CommandLine]","d":"little/cli/Application"},
{"l":"api/little/cli/Cli$.html","n":"Cli","t":"object Cli","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"application","t":"def application(usage: String): Application","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"application","t":"def application(usage: String, options: Options): Application","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"application","t":"def application(usage: String, options: Optionable*): Application","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"options","t":"def options(opts: Optionable*): Options","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"option","t":"def option(opt: String, description: String): Option","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"option","t":"def option(opt: String, hasArg: Boolean, description: String): Option","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"option","t":"def option(opt: String, longOpt: String, hasArg: Boolean, description: String): Option","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"group","t":"def group(opts: Option*): OptionGroup","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"parse","t":"def parse(opts: Options, args: Array[String]): CommandLine","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"parse","t":"def parse(opts: Options, args: Array[String], stoppable: Boolean): CommandLine","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"tryParse","t":"def tryParse(opts: Options, args: Array[String]): Try[CommandLine]","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"tryParse","t":"def tryParse(opts: Options, args: Array[String], stoppable: Boolean): Try[CommandLine]","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"printHelp","t":"def printHelp(usage: String, options: Options): Unit","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"printHelp","t":"def printHelp(usage: String, header: String, options: Options, footer: String): Unit","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"printHelp","t":"def printHelp(width: Int, usage: String, options: Options): Unit","d":"little/cli/Cli$"},
{"l":"api/little/cli/Cli$.html","n":"printHelp","t":"def printHelp(width: Int, usage: String, header: String, options: Options, footer: String): Unit","d":"little/cli/Cli$"},
{"l":"api/little/cli/Implicits$.html","n":"Implicits","t":"object Implicits","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$intValueMapper$.html","n":"intValueMapper","t":"given intValueMapper: ValueMapper[Int]","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$intValueMapper$.html","n":"map","t":"def map(value: String): Int","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$longValueMapper$.html","n":"longValueMapper","t":"given longValueMapper: ValueMapper[Long]","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$longValueMapper$.html","n":"map","t":"def map(value: String): Long","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$fileValueMapper$.html","n":"fileValueMapper","t":"given fileValueMapper: ValueMapper[File]","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$fileValueMapper$.html","n":"map","t":"def map(value: String): File","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$pathValueMapper$.html","n":"pathValueMapper","t":"given pathValueMapper: ValueMapper[Path]","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$pathValueMapper$.html","n":"map","t":"def map(value: String): Path","d":"little/cli/Implicits$"},
{"l":"api/little/cli/Implicits$$intValueMapper$.html","n":"intValueMapper","t":"given intValueMapper: ValueMapper[Int]","d":"little/cli/Implicits$$intValueMapper$"},
{"l":"api/little/cli/Implicits$$intValueMapper$.html","n":"map","t":"def map(value: String): Int","d":"little/cli/Implicits$$intValueMapper$"},
{"l":"api/little/cli/Implicits$$longValueMapper$.html","n":"longValueMapper","t":"given longValueMapper: ValueMapper[Long]","d":"little/cli/Implicits$$longValueMapper$"},
{"l":"api/little/cli/Implicits$$longValueMapper$.html","n":"map","t":"def map(value: String): Long","d":"little/cli/Implicits$$longValueMapper$"},
{"l":"api/little/cli/Implicits$$fileValueMapper$.html","n":"fileValueMapper","t":"given fileValueMapper: ValueMapper[File]","d":"little/cli/Implicits$$fileValueMapper$"},
{"l":"api/little/cli/Implicits$$fileValueMapper$.html","n":"map","t":"def map(value: String): File","d":"little/cli/Implicits$$fileValueMapper$"},
{"l":"api/little/cli/Implicits$$pathValueMapper$.html","n":"pathValueMapper","t":"given pathValueMapper: ValueMapper[Path]","d":"little/cli/Implicits$$pathValueMapper$"},
{"l":"api/little/cli/Implicits$$pathValueMapper$.html","n":"map","t":"def map(value: String): Path","d":"little/cli/Implicits$$pathValueMapper$"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"OptionType","t":"class OptionType(option: Option) extends AnyVal","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"args","t":"def args(count: Int): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"argName","t":"def argName(name: String): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"description","t":"def description(desc: String): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"longOpt","t":"def longOpt(name: String): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"optionalArg","t":"def optionalArg(optional: Boolean): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"required","t":"def required(mandatory: Boolean): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"optionType","t":"def optionType(optType: Class[_]): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"valueSeparator","t":"def valueSeparator(sep: Char): Option","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"mapValue","t":"def mapValue[T](implicit mapper: ValueMapper[T]): T","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionType.html","n":"mapValues","t":"def mapValues[T](implicit mapper: ValueMapper[T]): Seq[T]","d":"little/cli/Implicits$$OptionType"},
{"l":"api/little/cli/Implicits$$OptionGroupType.html","n":"OptionGroupType","t":"class OptionGroupType(group: OptionGroup) extends AnyVal","d":"little/cli/Implicits$$OptionGroupType"},
{"l":"api/little/cli/Implicits$$OptionGroupType.html","n":"+=","t":"def +=(opt: Option): OptionGroup","d":"little/cli/Implicits$$OptionGroupType"},
{"l":"api/little/cli/Implicits$$OptionGroupType.html","n":"required","t":"def required(mandatory: Boolean): OptionGroup","d":"little/cli/Implicits$$OptionGroupType"},
{"l":"api/little/cli/Implicits$$OptionsType.html","n":"OptionsType","t":"class OptionsType(options: Options) extends AnyVal","d":"little/cli/Implicits$$OptionsType"},
{"l":"api/little/cli/Implicits$$OptionsType.html","n":"+=","t":"def +=(opt: Option): Options","d":"little/cli/Implicits$$OptionsType"},
{"l":"api/little/cli/Implicits$$OptionsType.html","n":"+=","t":"def +=(group: OptionGroup): Options","d":"little/cli/Implicits$$OptionsType"},
{"l":"api/little/cli/Implicits$$OptionsType.html","n":"addOptions","t":"def addOptions(opts: Optionable*): Options","d":"little/cli/Implicits$$OptionsType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"CommandLineType","t":"class CommandLineType(command: CommandLine) extends AnyVal","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"getArgCount","t":"def getArgCount(): Int","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"getArg","t":"def getArg(index: Int): String","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"getArg","t":"def getArg(index: Int, default: => String): String","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapArg","t":"def mapArg[T](index: Int)(implicit mapper: ValueMapper[T]): T","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapArg","t":"def mapArg[T](index: Int, default: => T)(implicit mapper: ValueMapper[T]): T","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapArgs","t":"def mapArgs[T](implicit mapper: ValueMapper[T]): Seq[T]","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapOptionValue","t":"def mapOptionValue[T](opt: String)(implicit mapper: ValueMapper[T]): T","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapOptionValue","t":"def mapOptionValue[T](opt: String, default: => T)(implicit mapper: ValueMapper[T]): T","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"mapOptionValues","t":"def mapOptionValues[T](opt: String)(implicit mapper: ValueMapper[T]): Seq[T]","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"hasOptions","t":"def hasOptions(opts: Seq[String]): Tuple","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/Implicits$$CommandLineType.html","n":"hasOptions","t":"def hasOptions(one: String, more: String*): Tuple","d":"little/cli/Implicits$$CommandLineType"},
{"l":"api/little/cli/ValueMapper.html","n":"ValueMapper","t":"trait ValueMapper[T]","d":"little/cli/ValueMapper"},
{"l":"api/little/cli/ValueMapper.html","n":"map","t":"def map(value: String): T","d":"little/cli/ValueMapper"},
{"l":"api/index.html","n":"API","t":" API","d":"api"}];